---
repos:
  -
    hooks:
      -
        entry: "python -m pylint.__main__"
        id: pylint
        language: system
        name: pylint
        types:
          - python
    repo: local
default_language_version:
    python: python3.7
